GET /accounts/ACC-1001/balances HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJraWQiOiI3MTE1NmVl…
API-Version: 2

HTTP/1.1 200 OK
Content-Type: application/hal+json

{
  "_links": {
    "self": {
      "href": "http://localhost:8080/accounts/ACC-1001/balances"
    },
    "bk:account": {
      "href": "http://localhost:8080/accounts/ACC-1001"
    },
    "bk:positions": {
      "href": "http://localhost:8080/accounts/ACC-1001/positions"
    },
    "curies": [
      {
        "href": "https://docs.brokerage.example/rels/{rel}",
        "name": "bk",
        "templated": true
      }
    ]
  },
  "accountId": "ACC-1001",
  "currency": "USD",
  "cash": "32420.55",
  "reservedForOrders": "4800.00",
  "buyingPower": "55241.10",
  "positionsMarketValue": "34662.28",
  "totalEquity": "67082.83",
  "unrealizedPnl": "7042.98",
  "asOf": "2026-09-29T10:45:28.885254Z"
}
