GET /accounts/ACC-1001/order-events HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJraWQiOiI5ZjlkYzAw…
Accept: text/event-stream
Last-Event-ID: 7

HTTP/1.1 200 OK
Content-Type: text/event-stream

id:8
event:order.filled
data:{"orderId":"ORD-100004","status":"FILLED","filledQuantity":"4","remainingQuantity":"0","averageFillPrice":"185.3500","occurredAt":"2026-09-28T23:33:29.933320Z","_links":{"order":{"href":"http://localhost:8080/accounts/ACC-1001/orders/ORD-100004"}}}
