GET /accounts/ACC-1001/order-events HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJraWQiOiI3MTE1NmVl…
Accept: text/event-stream
Last-Event-ID: 7

HTTP/1.1 200 OK
Content-Type: text/event-stream

id:8
event:order.filled
data:{"orderId":"ORD-100004","status":"FILLED","filledQuantity":"4","remainingQuantity":"0","averageFillPrice":"185.5800","occurredAt":"2026-09-29T10:45:35.249581Z","_links":{"order":{"href":"http://localhost:8080/accounts/ACC-1001/orders/ORD-100004"}}}
