GET /instruments?symbol=AAPL HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJraWQiOiI3MTE1NmVl…
API-Version: 2

HTTP/1.1 200 OK
Content-Type: application/hal+json

{
  "_embedded": {
    "bk:instruments": [
      {
        "_links": {
          "self": {
            "href": "http://localhost:8080/instruments/EQ-AAPL"
          },
          "bk:quote": {
            "href": "http://localhost:8080/instruments/EQ-AAPL/quote"
          },
          "bk:option-chain": {
            "href": "http://localhost:8080/instruments/EQ-AAPL/option-chain{?expiration}",
            "templated": true
          }
        },
        "id": "EQ-AAPL",
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "type": "EQUITY",
        "exchange": "XNAS",
        "currency": "USD",
        "tradable": true,
        "fractionable": true,
        "multiplier": "1"
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/instruments?symbol=AAPL"
    },
    "curies": [
      {
        "href": "https://docs.brokerage.example/rels/{rel}",
        "name": "bk",
        "templated": true
      }
    ]
  }
}
