GET /accounts/ACC-1001/transactions?cursor=MTc4ODk0MjMyNjg3NjpUWE4tMTAwNw&limit=2 HTTP/1.1
Host: localhost:8080
Authorization: Bearer eyJraWQiOiI3MTE1NmVl…
API-Version: 2

HTTP/1.1 200 OK
Content-Type: application/hal+json

{
  "_embedded": {
    "bk:transactions": [
      {
        "id": "TXN-1006",
        "type": "DIVIDEND",
        "description": "Cash dividend AAPL",
        "amount": "13.00",
        "instrumentId": "EQ-AAPL",
        "symbol": "AAPL",
        "occurredAt": "2026-08-15T10:30:26.876245Z",
        "settlesOn": "2026-08-15"
      },
      {
        "id": "TXN-1002",
        "type": "DEPOSIT",
        "description": "ACH deposit",
        "amount": "10000.00",
        "occurredAt": "2026-06-01T06:45:26.876076Z",
        "settlesOn": "2026-06-02"
      }
    ]
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/accounts/ACC-1001/transactions?cursor=MTc4ODk0MjMyNjg3NjpUWE4tMTAwNw&limit=2"
    },
    "bk:account": {
      "href": "http://localhost:8080/accounts/ACC-1001"
    },
    "next": {
      "href": "http://localhost:8080/accounts/ACC-1001/transactions?cursor=MTc4MDI5NjMyNjg3NjpUWE4tMTAwMg&limit=2"
    },
    "curies": [
      {
        "href": "https://docs.brokerage.example/rels/{rel}",
        "name": "bk",
        "templated": true
      }
    ]
  }
}
